#!/usr/bin/env bash

THIS_DIR=$(cd $(dirname $0); pwd)
cd $THIS_DIR

 sudo apt-get upgrade -y
 
 #This is a helper for create anti spam bot.
 #created by: @janlou and powered by: @AdvanTm
 #warning: CopyRight all right reserved, we can block you channel or bot.
